<div class="page-content">
    <!-- Page Breadcrumb -->
    <div class="page-breadcrumbs">
        <ul class="breadcrumb">
            <li class="active">控制面板</li>
        </ul>
    </div>
    <!-- /Page Breadcrumb -->

    <!-- Page Body -->
    <div class="page-body">

        <div style="text-align:center; line-height:1000%; font-size:24px;">
            后台管理系统<br>
        </div>
    </div>
</div>